apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinsclaim
  namespace: jenkins
  labels:
    app: jenkins-master
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 10Gi
